/**
 * Known distillery official website URLs
 * Format: partial distillery name match → website URL
 */
export const DISTILLERY_URLS = {
  'aberfeldy': 'https://www.aberfeldy.com',
  'aberlour': 'https://www.aberlour.com',
  'akashi': 'https://www.eigashima.co.jp/en',
  'ardbeg': 'https://www.ardbeg.com',
  'arran': 'https://www.arranwhisky.com',
  'auchentoshan': 'https://www.auchentoshan.com',
  'balvenie': 'https://www.thebalvenie.com',
  'ballantine': 'https://www.ballantines.com',
  'bell': 'https://www.bellswhisky.com',
  'benriach': 'https://www.benriach.com',
  'benromach': 'https://www.benromach.com',
  'big peat': 'https://www.bigpeatwhisky.com',
  'bladnoch': 'https://www.bladnoch.com',
  'bowmore': 'https://www.bowmore.com',
  'bruichladdich': 'https://www.bruichladdich.com',
  'buffalo trace': 'https://www.buffalotracedistillery.com',
  'bulleit': 'https://www.bulleit.com',
  'bunnahabhain': 'https://www.bunnahabhain.com',
  'bushmills': 'https://www.bushmills.com',
  'caol ila': 'https://www.malts.com/en-us/brands/caol-ila',
  'cardhu': 'https://www.malts.com/en-us/brands/cardhu',
  'chivas': 'https://www.chivas.com',
  'chichibu': 'https://www.one-drinks.com/en/ichiros-malt',
  'clan macgregor': 'https://www.clanmacgregor.com',
  'clynelish': 'https://www.malts.com/en-us/brands/clynelish',
  'compass box': 'https://www.compassboxwhisky.com',
  'connemara': 'https://www.connemarapeatedwhiskey.com',
  'craigellachie': 'https://www.craigellachie.com',
  'cragganmore': 'https://www.malts.com/en-us/brands/cragganmore',
  'dalmore': 'https://www.thedalmore.com',
  'dalwhinnie': 'https://www.malts.com/en-us/brands/dalwhinnie',
  'dewar': 'https://www.dewars.com',
  'deanston': 'https://www.deanstondistillery.com',
  'edradour': 'https://www.edradour.com',
  'elijah craig': 'https://www.elijahcraig.com',
  'famous grouse': 'https://www.thefamousgrouse.com',
  'four roses': 'https://www.fourrosesbourbon.com',
  'glendronach': 'https://www.glendronachdistillery.com',
  'glenfarclas': 'https://www.glenfarclas.com',
  'glenfiddich': 'https://www.glenfiddich.com',
  'glengoyne': 'https://www.glengoyne.com',
  'glenkinchie': 'https://www.malts.com/en-us/brands/glenkinchie',
  'glenlivet': 'https://www.theglenlivet.com',
  'glenmorangie': 'https://www.glenmorangie.com',
  'glen moray': 'https://www.glenmoray.com',
  'glen grant': 'https://www.glengrant.com',
  'glen scotia': 'https://www.glenscotia.com',
  'golan heights': 'https://www.golanheightsdistillery.com',
  'green spot': 'https://www.singlepotstill.com',
  'hakushu': 'https://www.suntory.com/brands/hakushu',
  'heaven hill': 'https://www.heavenhilldistillery.com',
  'hibiki': 'https://www.suntory.com/brands/hibiki',
  'highland park': 'https://www.highlandparkwhisky.com',
  'jack daniel': 'https://www.jackdaniels.com',
  'jameson': 'https://www.jamesonwhiskey.com',
  'jim beam': 'https://www.jimbeam.com',
  'jura': 'https://www.jurawhisky.com',
  'johnnie walker': 'https://www.johnniewalker.com',
  'kavalan': 'https://www.kavalanwhisky.com',
  'kilchoman': 'https://www.kilchomandistillery.com',
  'kilkerran': 'https://www.kilkerran.scot',
  'knob creek': 'https://www.knobcreek.com',
  'knockando': 'https://www.malts.com/en-us/brands/knockando',
  'lagavulin': 'https://www.malts.com/en-us/brands/lagavulin',
  'laphroaig': 'https://www.laphroaig.com',
  'ledaig': 'https://www.tobermorydistillery.com',
  'macallan': 'https://www.themacallan.com',
  'maker\'s mark': 'https://www.makersmark.com',
  'makers mark': 'https://www.makersmark.com',
  'milk & honey': 'https://www.mh-distillery.com',
  'milk and honey': 'https://www.mh-distillery.com',
  'monkey shoulder': 'https://www.monkeyshoulder.com',
  'mortlach': 'https://www.malts.com/en-us/brands/mortlach',
  'nikka': 'https://www.nikka.com/eng',
  'oban': 'https://www.malts.com/en-us/brands/oban',
  'old pulteney': 'https://www.oldpulteney.com',
  'paul john': 'https://www.pauljohnwhisky.com',
  'port charlotte': 'https://www.bruichladdich.com/port-charlotte',
  'redbreast': 'https://www.redbreastwhiskey.com',
  'royal salute': 'https://www.royalsalute.com',
  'springbank': 'https://www.springbank.scot',
  'starward': 'https://www.starward.com.au',
  'talisker': 'https://www.malts.com/en-us/brands/talisker',
  'tamnavulin': 'https://www.tamnavulindistillery.com',
  'teacher': 'https://www.teacherswhisky.com',
  'teeling': 'https://www.teelingwhiskey.com',
  'the glenlivet': 'https://www.theglenlivet.com',
  'tobermory': 'https://www.tobermorydistillery.com',
  'togouchi': 'https://www.sakurao-d.com/en',
  'tomatin': 'https://www.tomatin.com',
  'tomintoul': 'https://www.tomintoul.com',
  'tullamore': 'https://www.tullamoredew.com',
  'wild turkey': 'https://www.wildturkeybourbon.com',
  'woodford reserve': 'https://www.woodfordreserve.com',
  'yamazaki': 'https://www.suntory.com/brands/yamazaki',
  'yoichi': 'https://www.nikka.com/eng/brands/yoichi',
}
